#!/bin/bash

for i in {1..15}; do
	cp input${i}.txt input.txt
	./a.out
	echo "-----------BEGIN input${i}-------------------\n"
	cat output.txt
	echo "\ncompare v\n"
	cat output${i}.txt
	echo "\n----------END----------------------\n"
done
